import { createThemeVariables, DEFAULT_THEME_VARIABLES } from "./colorTokens.js";

export const darkTheme = {
  section: "bg-bg text-text",

  card: "bg-white dark:bg-slate-900 border border-gray-200 dark:border-slate-700",

  textPrimary: "text-gray-900 dark:text-white",

  textSecondary: "text-gray-600 dark:text-gray-300",

  muted: "text-gray-500 dark:text-gray-400",

  buttonPrimary: "bg-blue-600 hover:bg-blue-700 text-white",

  buttonSecondary: "bg-gray-100 dark:bg-slate-800 text-gray-900 dark:text-white",
};

export const THEMES = {
  default: {
    id: "default",
    name: "Classic Slate",
    accent: "from-blue-500 to-indigo-600",
    colors: DEFAULT_THEME_VARIABLES,
  },
  "nova-cyberpunk": {
    id: "nova-cyberpunk",
    name: "Nova Cyberpunk",
    accent: "from-pink-500 to-purple-600",
    colors: {
      light: createThemeVariables({
        "--bg-color": "#0a0516",
        "--text-color": "#f5f3ff",
        "--text-color-light": "#d8b4fe",
        "--border-color": "#3b0764",
        "--card-bg-color": "#12072b",
        "--navbar-bg": "#0a0516",
        "--sidebar-bg": "#0e0624",
        "--input-bg": "#1d0e40",
        "--input-text": "#f5f3ff",
        "--table-bg": "#12072b",
        "--modal-bg": "#12072b",
        "--primary-color": "#ec4899",
        "--secondary-color": "#8b5cf6",
        "--accent-gradient": "linear-gradient(135deg, #ec4899 0%, #8b5cf6 100%)",
        "--glow-color": "rgba(236, 72, 153, 0.4)",
      }),
      dark: createThemeVariables({
        "--bg-color": "#0a0516",
        "--text-color": "#f5f3ff",
        "--text-color-light": "#d8b4fe",
        "--border-color": "#3b0764",
        "--card-bg-color": "#12072b",
        "--navbar-bg": "#0a0516",
        "--sidebar-bg": "#0e0624",
        "--input-bg": "#1d0e40",
        "--input-text": "#f5f3ff",
        "--table-bg": "#12072b",
        "--modal-bg": "#12072b",
        "--primary-color": "#ec4899",
        "--secondary-color": "#8b5cf6",
        "--accent-gradient": "linear-gradient(135deg, #ec4899 0%, #8b5cf6 100%)",
        "--glow-color": "rgba(236, 72, 153, 0.4)",
      }),
    },
  },
  "forest-mint": {
    id: "forest-mint",
    name: "Forest Mint",
    accent: "from-emerald-400 to-teal-600",
    colors: {
      light: createThemeVariables({
        "--bg-color": "#f0fdf4",
        "--text-color": "#14532d",
        "--text-color-light": "#15803d",
        "--border-color": "#bbf7d0",
        "--card-bg-color": "#ffffff",
        "--navbar-bg": "#f0fdf4",
        "--sidebar-bg": "#f0fdf4",
        "--input-bg": "#ffffff",
        "--input-text": "#14532d",
        "--table-bg": "#ffffff",
        "--modal-bg": "#ffffff",
        "--primary-color": "#10b981",
        "--secondary-color": "#047857",
        "--accent-gradient": "linear-gradient(135deg, #10b981 0%, #047857 100%)",
        "--glow-color": "rgba(16, 185, 129, 0.2)",
      }),
      dark: createThemeVariables({
        "--bg-color": "#06140e",
        "--text-color": "#f0fdf4",
        "--text-color-light": "#86efac",
        "--border-color": "#143a27",
        "--card-bg-color": "#0b2016",
        "--navbar-bg": "#06140e",
        "--sidebar-bg": "#081b12",
        "--input-bg": "#123324",
        "--input-text": "#f0fdf4",
        "--table-bg": "#0b2016",
        "--modal-bg": "#0b2016",
        "--primary-color": "#10b981",
        "--secondary-color": "#059669",
        "--accent-gradient": "linear-gradient(135deg, #10b981 0%, #059669 100%)",
        "--glow-color": "rgba(16, 185, 129, 0.4)",
      }),
    },
  },
  "sunset-amber": {
    id: "sunset-amber",
    name: "Sunset Amber",
    accent: "from-amber-500 to-orange-600",
    colors: {
      light: createThemeVariables({
        "--bg-color": "#fffbeb",
        "--text-color": "#78350f",
        "--text-color-light": "#b45309",
        "--border-color": "#fde68a",
        "--card-bg-color": "#ffffff",
        "--navbar-bg": "#fffbeb",
        "--sidebar-bg": "#fffbeb",
        "--input-bg": "#ffffff",
        "--input-text": "#78350f",
        "--table-bg": "#ffffff",
        "--modal-bg": "#ffffff",
        "--primary-color": "#f59e0b",
        "--secondary-color": "#b45309",
        "--accent-gradient": "linear-gradient(135deg, #f59e0b 0%, #ea580c 100%)",
        "--glow-color": "rgba(245, 158, 11, 0.2)",
      }),
      dark: createThemeVariables({
        "--bg-color": "#110b05",
        "--text-color": "#fffbeb",
        "--text-color-light": "#fcd34d",
        "--border-color": "#2c1c0a",
        "--card-bg-color": "#1a1107",
        "--navbar-bg": "#110b05",
        "--sidebar-bg": "#140e06",
        "--input-bg": "#25180b",
        "--input-text": "#fffbeb",
        "--table-bg": "#1a1107",
        "--modal-bg": "#1a1107",
        "--primary-color": "#f59e0b",
        "--secondary-color": "#ea580c",
        "--accent-gradient": "linear-gradient(135deg, #f59e0b 0%, #ea580c 100%)",
        "--glow-color": "rgba(245, 158, 11, 0.4)",
      }),
    },
  },
  "dracula-classic": {
    id: "dracula-classic",
    name: "Dracula Classic",
    accent: "from-pink-400 to-purple-500",
    colors: {
      light: createThemeVariables({
        "--bg-color": "#f8f8f2",
        "--text-color": "#282a36",
        "--text-color-light": "#6272a4",
        "--border-color": "#bd93f9",
        "--card-bg-color": "#ffffff",
        "--navbar-bg": "#f8f8f2",
        "--sidebar-bg": "#f8f8f2",
        "--input-bg": "#ffffff",
        "--input-text": "#282a36",
        "--table-bg": "#ffffff",
        "--modal-bg": "#ffffff",
        "--primary-color": "#bd93f9",
        "--secondary-color": "#ff79c6",
        "--accent-gradient": "linear-gradient(135deg, #ff79c6 0%, #bd93f9 100%)",
        "--glow-color": "rgba(189, 147, 249, 0.2)",
      }),
      dark: createThemeVariables({
        "--bg-color": "#1e1f29",
        "--text-color": "#f8f8f2",
        "--text-color-light": "#bd93f9",
        "--border-color": "#3d3e52",
        "--card-bg-color": "#282a36",
        "--navbar-bg": "#1e1f29",
        "--sidebar-bg": "#21222c",
        "--input-bg": "#343746",
        "--input-text": "#f8f8f2",
        "--table-bg": "#282a36",
        "--modal-bg": "#282a36",
        "--primary-color": "#bd93f9",
        "--secondary-color": "#ff79c6",
        "--accent-gradient": "linear-gradient(135deg, #ff79c6 0%, #bd93f9 100%)",
        "--glow-color": "rgba(189, 147, 249, 0.4)",
      }),
    },
  },
};
