name: Markdown Link Validator

on:
  push:
    branches: [ master ]
    paths:
      - '**/*.md'
  pull_request:
    branches: [ master ]
    paths:
      - '**/*.md'

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Markdown Link Checker
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          check-modified-files-only: 'yes'
          config-file: '.github/markdown-link-check-config.json'
